version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=e14f7b6f66c18d7b3dd7ca829373f3c936dca41f90915696219b7aad8f40c62a
      - JWT_EXPIRATION=3600000
      - SMTP_HOST=localhost
      - SMTP_PORT=25
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - UNIVERSITY_EMAIL=university@example.com
    depends_on:
      - db
    networks:
      - uniproject-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uniproject-network

networks:
  uniproject-network:
    driver: bridge

volumes:
  postgres_data: 